/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.governmentauctionrecords.forms;

import com.governmentauctionrecords.models.Auction;
import java.sql.Timestamp;
import java.text.SimpleDateFormat;
import java.util.Locale;
import javax.swing.text.DateFormatter;
import javax.swing.text.DefaultFormatterFactory;

/**
 *
 * @author carlo
 */
public class AddEditAuctionRecordForm extends javax.swing.JPanel {

    /**
     * Creates new form AddEditAuctionRecordForm
     */
    public AddEditAuctionRecordForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jTextFieldAuctionTitle = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaAuctionDescription = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jFormattedTextFieldAuctionDate = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        jFormattedTextFieldCreatedAt = new javax.swing.JFormattedTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldAuctionId = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        jLabel3.setText("Title:");

        jLabel4.setText("Description:");

        jTextAreaAuctionDescription.setColumns(20);
        jTextAreaAuctionDescription.setLineWrap(true);
        jTextAreaAuctionDescription.setRows(5);
        jScrollPane1.setViewportView(jTextAreaAuctionDescription);

        jLabel5.setText("Auction Date:");

        jFormattedTextFieldAuctionDate.setFormatterFactory(new DefaultFormatterFactory(new DateFormatter(new SimpleDateFormat("MM/dd/yyyy hh:mm a", Locale.US))));

        jLabel6.setText("Created At:");

        jFormattedTextFieldCreatedAt.setEditable(false);
        jFormattedTextFieldCreatedAt.setFormatterFactory(new DefaultFormatterFactory(new DateFormatter(new SimpleDateFormat("MM/dd/yyyy hh:mm a", Locale.US))));

        jLabel9.setText("ID:");

        jTextFieldAuctionId.setEditable(false);

        jLabel1.setText("(ID is auto-generated, leave empty)");

        jLabel2.setText("Required Format: MM/dd/yyyy hh:mm a");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel9))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldAuctionId)
                    .addComponent(jTextFieldAuctionTitle)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 321, Short.MAX_VALUE)
                    .addComponent(jFormattedTextFieldAuctionDate)
                    .addComponent(jFormattedTextFieldCreatedAt, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jTextFieldAuctionId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldAuctionTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jFormattedTextFieldAuctionDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jFormattedTextFieldCreatedAt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    public Auction getAuctionData() throws Exception {
        Auction auction = new Auction();

        String idText = jTextFieldAuctionId.getText().trim();
        if (!idText.isEmpty()) {
            auction.setId(Integer.parseInt(idText));
        } else {
            // ID not set for new inserts
            // Leave unset
        }
        auction.setTitle(jTextFieldAuctionTitle.getText().trim());
        auction.setDescription(jTextAreaAuctionDescription.getText().trim());

        SimpleDateFormat sdf = new SimpleDateFormat("MM/dd/yyyy hh:mm a");

        String auctionDateText = jFormattedTextFieldAuctionDate.getText().trim();
        if (!auctionDateText.isEmpty()) {
            auction.setAuctionDate(new Timestamp(sdf.parse(auctionDateText).getTime()));
        } else {
            auction.setAuctionDate(null);
        }

        String createdAtText = jFormattedTextFieldCreatedAt.getText().trim();
        if (!createdAtText.isEmpty()) {
            auction.setCreatedAt(new Timestamp(sdf.parse(createdAtText).getTime()));
        } else {
            auction.setCreatedAt(new Timestamp(System.currentTimeMillis()));
        }

        return auction;
    }

    public void setAuctionData(Auction auction) {
        if (auction == null) {
            return;
        }

        jTextFieldAuctionId.setText(Integer.toString(auction.getId()));
        jTextFieldAuctionTitle.setText(auction.getTitle());
        jTextAreaAuctionDescription.setText(auction.getDescription());
        jTextAreaAuctionDescription.setCaretPosition(0); // go back to the start

        SimpleDateFormat sdf = new SimpleDateFormat("MM/dd/yyyy hh:mm a");

        if (auction.getAuctionDate() != null) {
            jFormattedTextFieldAuctionDate.setText(sdf.format(auction.getAuctionDate()));
        } else {
            jFormattedTextFieldAuctionDate.setText("");
        }

        if (auction.getCreatedAt() != null) {
            jFormattedTextFieldCreatedAt.setText(sdf.format(auction.getCreatedAt()));
        } else {
            jFormattedTextFieldCreatedAt.setText("");
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField jFormattedTextFieldAuctionDate;
    private javax.swing.JFormattedTextField jFormattedTextFieldCreatedAt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaAuctionDescription;
    private javax.swing.JTextField jTextFieldAuctionId;
    private javax.swing.JTextField jTextFieldAuctionTitle;
    // End of variables declaration//GEN-END:variables
}
