/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.governmentauctionrecords.forms;

import java.awt.Toolkit;
import java.awt.event.MouseEvent;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.awt.print.PrinterException;
import java.io.File;
import java.text.SimpleDateFormat;
import java.util.Locale;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import com.governmentauctionrecords.daos.AuctionDAO;
import com.governmentauctionrecords.daos.BidDAO;
import com.governmentauctionrecords.models.Auction;
import com.governmentauctionrecords.models.Bid;
import com.governmentauctionrecords.utils.MultiColumnBidsJListRenderer;
import java.awt.Font;
import java.math.BigDecimal;
import java.sql.SQLException;
import java.sql.Timestamp;
import java.text.NumberFormat;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Date;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.JTextArea;
import javax.swing.text.DateFormatter;
import javax.swing.text.DefaultFormatterFactory;

/**
 *
 * @author carlo
 */
public class MainApplicationForm extends javax.swing.JFrame {

    private int currentRecordId = 0;
    private Timestamp currentRecordCreatedAtTimestamp = null;

    // Constants for column widths
    final int BIDDER_NAME_WIDTH = 25;
    final int BID_AMOUNT_WIDTH = 15;
    final int DESCRIPTION_WIDTH = 50; // optional wrapping for description

    /**
     * Creates new form MainApplicationForm
     */
    public MainApplicationForm() {

        initComponents();

        setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                promptQuit(MainApplicationForm.this);
            }
        });

        // Load initial (latest) record on startup
        loadRecord(null, null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenuForEditorPane = new javax.swing.JPopupMenu();
        jMenuItemCopy = new javax.swing.JMenuItem();
        jMenuItemSelectAll = new javax.swing.JMenuItem();
        jMenuItemPrint = new javax.swing.JMenuItem();
        jPanelBidRecordListHeader = new javax.swing.JPanel();
        jLabelBidRecordsListHeaderBidderName = new javax.swing.JLabel();
        buttonGroupLookAndFeelOptions = new javax.swing.ButtonGroup();
        jTabbedPaneFormPages = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldAuctionTitle = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaAuctionDescription = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jFormattedTextFieldAuctionDate = new javax.swing.JFormattedTextField();
        jFormattedTextFieldCreatedAt = new javax.swing.JFormattedTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextFieldAuctionId = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jScrollPaneBidRecords = new javax.swing.JScrollPane();
        jListBidRecords = new javax.swing.JList<>();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jEditorPaneHelpContents = new javax.swing.JEditorPane();
        jPanel5 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jRadioButtonMetalLaf = new javax.swing.JRadioButton();
        jRadioButtonWindowsClassicLaf = new javax.swing.JRadioButton();
        jButtonEditRecord = new javax.swing.JButton();
        jButtonDeleteRecord = new javax.swing.JButton();
        jButtonAddRecord = new javax.swing.JButton();
        jButtonPreviousRecord = new javax.swing.JButton();
        jButtonNextRecord = new javax.swing.JButton();
        jLabelPreviousIcon = new javax.swing.JLabel();
        jLabelNextIcon = new javax.swing.JLabel();
        jPanelRecordPrintOptions = new javax.swing.JPanel();
        jCheckBoxIncludeAuctionBidRecords = new javax.swing.JCheckBox();
        jButtonPrintRecord = new javax.swing.JButton();
        jButtonExit = new javax.swing.JButton();
        jButtonSearchRecord = new javax.swing.JButton();

        jMenuItemCopy.setText("Copy");
        jMenuItemCopy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCopyActionPerformed(evt);
            }
        });
        jPopupMenuForEditorPane.add(jMenuItemCopy);

        jMenuItemSelectAll.setText("Select All");
        jMenuItemSelectAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSelectAllActionPerformed(evt);
            }
        });
        jPopupMenuForEditorPane.add(jMenuItemSelectAll);

        jMenuItemPrint.setText("Print");
        jMenuItemPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPrintActionPerformed(evt);
            }
        });
        jPopupMenuForEditorPane.add(jMenuItemPrint);

        jPanelBidRecordListHeader.setLayout(new java.awt.GridLayout(1, 0));

        jLabelBidRecordsListHeaderBidderName.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelBidRecordsListHeaderBidderName.setText("Below is a list of all the current Auction bidders and their amounts.");
        jLabelBidRecordsListHeaderBidderName.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanelBidRecordListHeader.add(jLabelBidRecordsListHeaderBidderName);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Goverment Auction Records");
        setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        setIconImage(new ImageIcon("C:\\Users\\carlo\\OneDrive\\Documents\\NetBeansProjects\\GovernmentAuctionRecordsApp\\src\\main\\resources\\images\\vb6.png").getImage());

        jTabbedPaneFormPages.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jTabbedPaneFormPagesStateChanged(evt);
            }
        });

        jLabel3.setText("Title:");

        jTextFieldAuctionTitle.setEditable(false);

        jLabel4.setText("Description:");

        jTextAreaAuctionDescription.setEditable(false);
        jTextAreaAuctionDescription.setColumns(20);
        jTextAreaAuctionDescription.setRows(5);
        jScrollPane1.setViewportView(jTextAreaAuctionDescription);

        jLabel5.setText("Auction Date:");

        jLabel6.setText("Created At:");

        jFormattedTextFieldAuctionDate.setEditable(false);
        jFormattedTextFieldAuctionDate.setFormatterFactory(new DefaultFormatterFactory(new DateFormatter(new SimpleDateFormat("MM/dd/yyyy hh:mm a", Locale.US))));

        jFormattedTextFieldCreatedAt.setEditable(false);
        jFormattedTextFieldCreatedAt.setFormatterFactory(new DefaultFormatterFactory(new DateFormatter(new SimpleDateFormat("MM/dd/yyyy hh:mm a", Locale.US))));

        jLabel10.setText("ID:");

        jTextFieldAuctionId.setEditable(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel10))
                .addGap(43, 43, 43)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldAuctionId)
                    .addComponent(jTextFieldAuctionTitle)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 331, Short.MAX_VALUE)
                    .addComponent(jFormattedTextFieldAuctionDate)
                    .addComponent(jFormattedTextFieldCreatedAt, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jTextFieldAuctionId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldAuctionTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jFormattedTextFieldAuctionDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jFormattedTextFieldCreatedAt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(155, Short.MAX_VALUE))
        );

        jTabbedPaneFormPages.addTab("Auction Records", jPanel2);

        jScrollPaneBidRecords.setColumnHeaderView(jPanelBidRecordListHeader);

        jListBidRecords.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPaneBidRecords.setViewportView(jListBidRecords);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPaneBidRecords, javax.swing.GroupLayout.DEFAULT_SIZE, 436, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPaneBidRecords, javax.swing.GroupLayout.DEFAULT_SIZE, 372, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPaneFormPages.addTab("Bid Records", jPanel3);

        jEditorPaneHelpContents.setEditable(false);
        jEditorPaneHelpContents.setContentType("text/html"); // NOI18N
        try {
            jEditorPaneHelpContents.setPage(new File("C:\\Users\\carlo\\OneDrive\\Documents\\NetBeansProjects\\GovernmentAuctionRecordsApp\\src\\main\\resources\\html\\HelpContents.html").toURI().toURL());
        } catch (java.io.IOException e1) {
            e1.printStackTrace();
        }
        jEditorPaneHelpContents.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jEditorPaneHelpContentsMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jEditorPaneHelpContentsMouseReleased(evt);
            }
        });
        jScrollPane3.setViewportView(jEditorPaneHelpContents);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 456, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 394, Short.MAX_VALUE)
        );

        jTabbedPaneFormPages.addTab("Help Contents", jPanel4);

        jLabel9.setText("Change the Look And Feel (LAF) of this application's interface.");

        buttonGroupLookAndFeelOptions.add(jRadioButtonMetalLaf);
        jRadioButtonMetalLaf.setText("Metal (Default)");
        jRadioButtonMetalLaf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMetalLafActionPerformed(evt);
            }
        });

        buttonGroupLookAndFeelOptions.add(jRadioButtonWindowsClassicLaf);
        jRadioButtonWindowsClassicLaf.setSelected(true);
        jRadioButtonWindowsClassicLaf.setText("Windows Classic");
        jRadioButtonWindowsClassicLaf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonWindowsClassicLafActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButtonWindowsClassicLaf)
                            .addComponent(jRadioButtonMetalLaf))))
                .addContainerGap(151, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addComponent(jRadioButtonMetalLaf)
                .addGap(18, 18, 18)
                .addComponent(jRadioButtonWindowsClassicLaf)
                .addContainerGap(287, Short.MAX_VALUE))
        );

        jTabbedPaneFormPages.addTab("Application Settings", jPanel5);

        jButtonEditRecord.setText("Edit Record");
        jButtonEditRecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditRecordActionPerformed(evt);
            }
        });

        jButtonDeleteRecord.setText("Delete Record");
        jButtonDeleteRecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteRecordActionPerformed(evt);
            }
        });

        jButtonAddRecord.setText("Add Record");
        jButtonAddRecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddRecordActionPerformed(evt);
            }
        });

        jButtonPreviousRecord.setText("Previous Record");
        jButtonPreviousRecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPreviousRecordActionPerformed(evt);
            }
        });

        jButtonNextRecord.setText("Next Record");
        jButtonNextRecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNextRecordActionPerformed(evt);
            }
        });

        jLabelPreviousIcon.setIcon(new javax.swing.ImageIcon("C:\\Users\\carlo\\OneDrive\\Documents\\NetBeansProjects\\GovernmentAuctionRecordsApp\\src\\main\\resources\\images\\arrow-left-icon.png")); // NOI18N

        jLabelNextIcon.setIcon(new javax.swing.ImageIcon("C:\\Users\\carlo\\OneDrive\\Documents\\NetBeansProjects\\GovernmentAuctionRecordsApp\\src\\main\\resources\\images\\arrow-right-icon.png")); // NOI18N

        jPanelRecordPrintOptions.setBorder(javax.swing.BorderFactory.createTitledBorder("Record Print Options"));

        jCheckBoxIncludeAuctionBidRecords.setText("Include Bid Records");

        jButtonPrintRecord.setText("Print");
        jButtonPrintRecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPrintRecordActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelRecordPrintOptionsLayout = new javax.swing.GroupLayout(jPanelRecordPrintOptions);
        jPanelRecordPrintOptions.setLayout(jPanelRecordPrintOptionsLayout);
        jPanelRecordPrintOptionsLayout.setHorizontalGroup(
            jPanelRecordPrintOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRecordPrintOptionsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelRecordPrintOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonPrintRecord, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jCheckBoxIncludeAuctionBidRecords))
                .addContainerGap())
        );
        jPanelRecordPrintOptionsLayout.setVerticalGroup(
            jPanelRecordPrintOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRecordPrintOptionsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jCheckBoxIncludeAuctionBidRecords)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonPrintRecord, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jButtonExit.setMnemonic('x');
        jButtonExit.setText("Exit");
        jButtonExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExitActionPerformed(evt);
            }
        });

        jButtonSearchRecord.setText("Search Record");
        jButtonSearchRecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSearchRecordActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelPreviousIcon)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonPreviousRecord, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonNextRecord, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelNextIcon)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jTabbedPaneFormPages))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jButtonEditRecord, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonDeleteRecord, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                        .addComponent(jButtonAddRecord, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                        .addComponent(jButtonExit, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                        .addComponent(jButtonSearchRecord, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanelRecordPrintOptions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTabbedPaneFormPages))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jButtonSearchRecord, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonEditRecord, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonDeleteRecord, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonAddRecord, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonExit, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanelRecordPrintOptions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtonPreviousRecord, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonNextRecord, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabelPreviousIcon, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelNextIcon, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExitActionPerformed
        promptQuit(this);
    }//GEN-LAST:event_jButtonExitActionPerformed

    private void jMenuItemCopyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCopyActionPerformed
        jEditorPaneHelpContents.copy();
    }//GEN-LAST:event_jMenuItemCopyActionPerformed

    private void jMenuItemSelectAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSelectAllActionPerformed
        jEditorPaneHelpContents.selectAll();
    }//GEN-LAST:event_jMenuItemSelectAllActionPerformed

    private void jEditorPaneHelpContentsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jEditorPaneHelpContentsMousePressed
        showPopupMenu(evt);
    }//GEN-LAST:event_jEditorPaneHelpContentsMousePressed

    private void jEditorPaneHelpContentsMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jEditorPaneHelpContentsMouseReleased
        showPopupMenu(evt);
    }//GEN-LAST:event_jEditorPaneHelpContentsMouseReleased

    private void jMenuItemPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPrintActionPerformed
        // The built-in JEditorPane.print() can be slow with HTML content because 
        // it renders and paginates the styled content before showing the dialog.
        // This is a common issue especially if the HTML/CSS is complex or the 
        // document is long. Also, Swing’s JEditorPane.print() does not provide 
        // any real progress events or callbacks to monitor the actual print job
        // progress. Swing’s printing API (print() method) is a blocking call 
        // that internally renders pages and sends them to the printer. 
        // There’s no built-in mechanism to get “percent done” updates from 
        // JEditorPane.print(). To solve this, we launch printing in a background 
        // thread to avoid UI freeze and create a modal dialog to show during printing.

        JDialog printingDialog = new JDialog(this, "Printing", true);
        JLabel label = new JLabel("Sending print job, please wait...");
        label.setBorder(BorderFactory.createEmptyBorder(20, 20, 20, 20));
        printingDialog.add(label);
        printingDialog.pack();
        printingDialog.setLocationRelativeTo(this);

        // Run printing on a background thread
        new Thread(() -> {
            try {
                boolean done = jEditorPaneHelpContents.print();

                // Close dialog and show result on EDT
                SwingUtilities.invokeLater(() -> {
                    printingDialog.dispose();

                    if (done) {
                        JOptionPane.showMessageDialog(this,
                                "Printing completed successfully.",
                                "Information",
                                JOptionPane.INFORMATION_MESSAGE);
                    } else {
                        JOptionPane.showMessageDialog(this,
                                "Print cancelled.",
                                "Warning",
                                JOptionPane.WARNING_MESSAGE);
                    }
                });
            } catch (PrinterException ex) {
                SwingUtilities.invokeLater(() -> {
                    printingDialog.dispose();
                    JOptionPane.showMessageDialog(this,
                            "Printing failed: " + ex.getMessage(),
                            "Error",
                            JOptionPane.ERROR_MESSAGE);
                });
            }
        }).start();

        // Show the dialog (blocks UI until disposed)
        printingDialog.setVisible(true);

    }//GEN-LAST:event_jMenuItemPrintActionPerformed

    private void jRadioButtonMetalLafActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMetalLafActionPerformed
        try {
            // Switch to Metal Look and Feel
            UIManager.setLookAndFeel("javax.swing.plaf.metal.MetalLookAndFeel");

            // Update all UI components in the frame
            SwingUtilities.updateComponentTreeUI(this);
        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Failed to change Look and Feel: " + ex.getMessage());
        }
    }//GEN-LAST:event_jRadioButtonMetalLafActionPerformed

    private void jRadioButtonWindowsClassicLafActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonWindowsClassicLafActionPerformed
        try {
            // Switch to Windows Classic Look and Feel
            UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsClassicLookAndFeel");

            // Update all UI components in the frame
            SwingUtilities.updateComponentTreeUI(this);
        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Failed to change Look and Feel: " + ex.getMessage());
        }
    }//GEN-LAST:event_jRadioButtonWindowsClassicLafActionPerformed

    private void jButtonPreviousRecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPreviousRecordActionPerformed
        loadRecord(currentRecordCreatedAtTimestamp, jButtonPreviousRecord);
    }//GEN-LAST:event_jButtonPreviousRecordActionPerformed

    private void jButtonNextRecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNextRecordActionPerformed
        loadRecord(currentRecordCreatedAtTimestamp, jButtonNextRecord);
    }//GEN-LAST:event_jButtonNextRecordActionPerformed

    private void jButtonAddRecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddRecordActionPerformed
        String commandButtons[] = {"Submit", "Cancel"};
        AddEditAuctionRecordForm form = new AddEditAuctionRecordForm();
        int promptResult
                = JOptionPane.showOptionDialog(
                        this,
                        form,
                        "Add New Auction Record",
                        JOptionPane.DEFAULT_OPTION,
                        JOptionPane.INFORMATION_MESSAGE,
                        null,
                        commandButtons,
                        null);
        if (promptResult == JOptionPane.YES_OPTION) {
            try {
                Auction auction = form.getAuctionData();

                int newId = AuctionDAO.insertAuction(auction);

                if (newId > 0) {
                    JOptionPane.showMessageDialog(this,
                            "Auction inserted successfully with ID: " + newId,
                            "Success",
                            JOptionPane.INFORMATION_MESSAGE);

                    // After insert, load the latest auction (which will be the one just added)
                    Auction latestAuction = AuctionDAO.getLatestAuction();
                    if (latestAuction != null) {
                        populateForm(latestAuction);
                        updateNavigationButtons(latestAuction.getCreatedAt());
                    } else {
                        JOptionPane.showMessageDialog(this,
                                "Could not reload the newly inserted auction.",
                                "Warning",
                                JOptionPane.WARNING_MESSAGE);
                    }
                } else {
                    JOptionPane.showMessageDialog(this,
                            "Failed to insert auction record.",
                            "Error",
                            JOptionPane.ERROR_MESSAGE);
                }
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this,
                        "Invalid input: " + ex.getMessage(),
                        "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_jButtonAddRecordActionPerformed

    private void jButtonEditRecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditRecordActionPerformed
        String commandButtons[] = {"Submit", "Cancel"};
        AddEditAuctionRecordForm form = new AddEditAuctionRecordForm();

        // Pre-fill the form with current record
        Auction current = new Auction();
        current.setId(Integer.parseInt(jTextFieldAuctionId.getText().trim()));
        current.setTitle(jTextFieldAuctionTitle.getText().trim());
        current.setDescription(jTextAreaAuctionDescription.getText().trim());

        SimpleDateFormat sdf = new SimpleDateFormat("MM/dd/yyyy hh:mm a");

        try {
            String auctionDateText = jFormattedTextFieldAuctionDate.getText().trim();
            if (!auctionDateText.isEmpty()) {
                current.setAuctionDate(new Timestamp(sdf.parse(auctionDateText).getTime()));
            } else {
                current.setAuctionDate(null);
            }
        } catch (Exception e) {
            current.setAuctionDate(null);
        }

        try {
            String createdAtText = jFormattedTextFieldCreatedAt.getText().trim();
            if (!createdAtText.isEmpty()) {
                current.setCreatedAt(new Timestamp(sdf.parse(createdAtText).getTime()));
            } else {
                current.setCreatedAt(null);
            }
        } catch (Exception e) {
            current.setCreatedAt(null);
        }

        form.setAuctionData(current);

        int promptResult = JOptionPane.showOptionDialog(
                this,
                form,
                "Edit Auction Record",
                JOptionPane.DEFAULT_OPTION,
                JOptionPane.INFORMATION_MESSAGE,
                null,
                commandButtons,
                null);

        if (promptResult == JOptionPane.YES_OPTION) {
            try {
                Auction edited = form.getAuctionData();

                boolean updated = AuctionDAO.updateAuction(edited);

                if (updated) {
                    JOptionPane.showMessageDialog(this,
                            "Auction updated successfully!",
                            "Success",
                            JOptionPane.INFORMATION_MESSAGE);

                    // Immediately reflect the updated values on the form
                    populateForm(edited);

                    // Recompute prev/next availability based on (possibly changed) CreatedAt
                    updateNavigationButtons(edited.getCreatedAt());

                    // (Optional) If you prefer to show whatever is newest after an edit:
                    // Auction latest = AuctionDAO.getLatestAuction();
                    // if (latest != null) {
                    //     populateForm(latest);
                    //     updateNavigationButtons(latest.getCreatedAt());
                    // }
                } else {
                    JOptionPane.showMessageDialog(this,
                            "No auction was updated (check the ID).",
                            "Update Failed",
                            JOptionPane.WARNING_MESSAGE);
                }

            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this,
                        "Invalid input: " + ex.getMessage(),
                        "Error",
                        JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_jButtonEditRecordActionPerformed

    private void jButtonDeleteRecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteRecordActionPerformed
        Toolkit.getDefaultToolkit().beep();
        String objButtons[] = {"Delete Record", "Cancel"};
        int promptResult
                = JOptionPane.showOptionDialog(
                        this,
                        "Are you sure you wish to delete this record?",
                        "Delete Confirmation",
                        JOptionPane.DEFAULT_OPTION,
                        JOptionPane.QUESTION_MESSAGE,
                        null,
                        objButtons,
                        objButtons[1]);
        if (promptResult == JOptionPane.YES_OPTION) {
            try {
                boolean deleted = AuctionDAO.deleteAuction(currentRecordId);

                if (deleted) {
                    JOptionPane.showMessageDialog(this,
                            "Auction deleted successfully!",
                            "Success",
                            JOptionPane.INFORMATION_MESSAGE);

                    // Navigate to Latest auction after deletion
                    loadRecord(null, null);
                } else {
                    JOptionPane.showMessageDialog(this,
                            "No auction was deleted (check the ID).",
                            "Update Failed",
                            JOptionPane.WARNING_MESSAGE);
                }

            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this,
                        "Error deleting record: " + ex.getMessage(),
                        "Error",
                        JOptionPane.ERROR_MESSAGE);
            }

        }
    }//GEN-LAST:event_jButtonDeleteRecordActionPerformed

    private void jButtonPrintRecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPrintRecordActionPerformed
        Auction auctionToPrint = new Auction();
        auctionToPrint.setTitle(jTextFieldAuctionTitle.getText());
        auctionToPrint.setDescription(jTextAreaAuctionDescription.getText());

        SimpleDateFormat sdf = new SimpleDateFormat("MM/dd/yyyy hh:mm a");

        try {
            String auctionDateText = jFormattedTextFieldAuctionDate.getText().trim();
            if (!auctionDateText.isEmpty()) {
                auctionToPrint.setAuctionDate(new Timestamp(sdf.parse(auctionDateText).getTime()));
            } else {
                auctionToPrint.setAuctionDate(null);
            }
        } catch (Exception e) {
            auctionToPrint.setAuctionDate(null); // or handle error as needed
        }

        try {
            String createdAtText = jFormattedTextFieldCreatedAt.getText().trim();
            if (!createdAtText.isEmpty()) {
                auctionToPrint.setCreatedAt(new Timestamp(sdf.parse(createdAtText).getTime()));
            } else {
                auctionToPrint.setCreatedAt(null);
            }
        } catch (Exception e) {
            auctionToPrint.setCreatedAt(null);
        }
        // Use our custom Printable and call PrinterJob.print(),
        // where Java uses the lower-level AWT printing API, which shows the 
        // native OS print dialog. This dialog is more generic and lower-level,
        // less polished than the Swing print() dialog on text components.
        //        PrinterJob job = PrinterJob.getPrinterJob();
        //        job.setPrintable(new AuctionRecordPrinter(auctionToPrint));
        //
        //        boolean doPrint = job.printDialog();
        //        if (doPrint) {
        //            try {
        //                job.print();
        //            } catch (PrinterException e) {
        //                e.printStackTrace();
        //                // handle error
        //            }
        //        }

        // Recommended uniform width for headers/footers
        int lineWidth = 50;
        String line = "=".repeat(lineWidth);

        // Start building the professional printout
        StringBuilder sb = new StringBuilder();

        // Header
        sb.append(line).append("\n");
        // Centered header text
        sb.append(String.format("%" + ((lineWidth + "AUCTION RECORD".length()) / 2) + "s%n", "AUCTION RECORD"));
        sb.append(line).append("\n\n");

        // Auction info
        sb.append(String.format("Auction ID    : %d%n", currentRecordId));

        // Wrap Title if too long
        List<String> titleLines = wrapText(auctionToPrint.getTitle(), DESCRIPTION_WIDTH);
        sb.append("Title         : ").append(titleLines.get(0)).append("\n");
        for (int i = 1; i < titleLines.size(); i++) {
            sb.append("                ").append(titleLines.get(i)).append("\n");
        }

        // Wrap Description if too long
        List<String> descriptionLines = wrapText(auctionToPrint.getDescription(), DESCRIPTION_WIDTH);
        sb.append("Description   : ").append(descriptionLines.get(0)).append("\n");
        for (int i = 1; i < descriptionLines.size(); i++) {
            sb.append("                ").append(descriptionLines.get(i)).append("\n");
        }
        
        // Wrap and justify Description
//        int descriptionWidth = lineWidth - 16; // leave space for "Description   : "
//        List<String> descriptionLines = justifyText(auctionToPrint.getDescription(), descriptionWidth);
//
//        sb.append("Description   : ").append(descriptionLines.get(0)).append("\n");
//        for (int i = 1; i < descriptionLines.size(); i++) {
//            sb.append("                ").append(descriptionLines.get(i)).append("\n");
//        }

        // Auction and creation timestamps
        sb.append(String.format("Auction Date  : %s%n", auctionToPrint.getAuctionDate() != null ? sdf.format(auctionToPrint.getAuctionDate()) : "N/A"));
        sb.append(String.format("Created At    : %s%n", auctionToPrint.getCreatedAt() != null ? sdf.format(auctionToPrint.getCreatedAt()) : "N/A"));
        sb.append("\n");

        // Include bids if checkbox checked
        if (jCheckBoxIncludeAuctionBidRecords.isSelected()) {
            try {
                List<Bid> bids = BidDAO.getBidsForAuction(currentRecordId);
                if (!bids.isEmpty()) {
                    sb.append(line).append("\n");
                    sb.append(String.format("%" + ((lineWidth + "BIDS".length()) / 2) + "s%n", "BIDS")); // centered
                    sb.append(line).append("\n");

                    // Header row
                    sb.append(String.format("%-" + BIDDER_NAME_WIDTH + "s | %" + BID_AMOUNT_WIDTH + "s%n", "Bidder Name", "Bid Amount"));
                    int tableWidth = BIDDER_NAME_WIDTH + BID_AMOUNT_WIDTH + 3; // 3 for " | "
                    sb.append("-".repeat(tableWidth)).append("\n");

                    BigDecimal highestBid = BigDecimal.ZERO;
                    BigDecimal totalBidAmount = BigDecimal.ZERO;

                    for (Bid bid : bids) {
                        // Wrap bidder name if too long
                        List<String> nameLines = wrapText(bid.getBidderName(), BIDDER_NAME_WIDTH);
                        String formattedAmount = NumberFormat.getCurrencyInstance().format(bid.getBidAmount());

                        for (int i = 0; i < nameLines.size(); i++) {
                            if (i == 0) {
                                // First line: show bidder name + bid amount
                                sb.append(String.format("%-" + BIDDER_NAME_WIDTH + "s | %" + BID_AMOUNT_WIDTH + "s%n", nameLines.get(i), formattedAmount));
                            } else {
                                // Subsequent lines: only show bidder name continuation
                                sb.append(String.format("%-" + BIDDER_NAME_WIDTH + "s | %" + BID_AMOUNT_WIDTH + "s%n", nameLines.get(i), ""));
                            }
                        }

                        if (bid.getBidAmount().compareTo(highestBid) > 0) {
                            highestBid = bid.getBidAmount();
                        }

                        totalBidAmount = totalBidAmount.add(bid.getBidAmount()); // sum all bids
                    }

                    sb.append("-".repeat(tableWidth)).append("\n");
                    sb.append(String.format("Total Bids       : %d%n", bids.size()));
                    sb.append(String.format("Highest Bid      : %s%n", NumberFormat.getCurrencyInstance().format(highestBid)));
                    sb.append(String.format("Total of Bids    : %s%n", NumberFormat.getCurrencyInstance().format(totalBidAmount)));
                } else {
                    sb.append("No bids found for this auction.\n\n");
                }
            } catch (SQLException ex) {
                ex.printStackTrace();
                sb.append("\nError fetching bids: ").append(ex.getMessage()).append("\n");
            }
        }

        // Footer
        sb.append(line).append("\n");
        // Center footer text correctly
        String footerText = "END OF AUCTION RECORD";
        int padding = (lineWidth - footerText.length()) / 2;
        sb.append(" ".repeat(padding)).append(footerText).append("\n");
        sb.append(line).append("\n");

        // Use Swing, where it uses its own built-in printing implementation 
        // specifically tailored for text components. This method handles 
        // pagination, font styles, and the print dialog with features optimized 
        // for printing text, including headers, footers, and selections.
        JTextArea printArea = new JTextArea(sb.toString());
        printArea.setFont(new Font("Monospaced", Font.PLAIN, 12)); // monospaced for neat alignment

        try {
            boolean done = printArea.print();
            if (done) {
                System.out.println("Printing completed");
            } else {
                System.out.println("Printing canceled");
            }
        } catch (PrinterException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Printing error: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_jButtonPrintRecordActionPerformed

    private void jTabbedPaneFormPagesStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jTabbedPaneFormPagesStateChanged
        int selectedIndex = jTabbedPaneFormPages.getSelectedIndex();
        
        boolean isFirstOrSecondTabSelected = selectedIndex == 0 || selectedIndex == 1;
        
        jButtonSearchRecord.setVisible(isFirstOrSecondTabSelected);
        jButtonAddRecord.setVisible(isFirstOrSecondTabSelected);
        jButtonEditRecord.setVisible(isFirstOrSecondTabSelected);
        jButtonDeleteRecord.setVisible(isFirstOrSecondTabSelected);
        jPanelRecordPrintOptions.setVisible(isFirstOrSecondTabSelected);
        jLabelPreviousIcon.setVisible(isFirstOrSecondTabSelected);
        jButtonPreviousRecord.setVisible(isFirstOrSecondTabSelected);
        jLabelNextIcon.setVisible(isFirstOrSecondTabSelected);
        jButtonNextRecord.setVisible(isFirstOrSecondTabSelected);
        
    }//GEN-LAST:event_jTabbedPaneFormPagesStateChanged

    private void jButtonSearchRecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSearchRecordActionPerformed
        String searchInput = JOptionPane.showInputDialog(this,
                "Enter record ID or Title as search criteria:",
                "Record Search",
                JOptionPane.QUESTION_MESSAGE);

        if (searchInput != null && !searchInput.trim().isBlank()) {
            try {
                Auction foundRecord = AuctionDAO.searchAuction(searchInput);
                if (foundRecord != null) {
                    populateForm(foundRecord);
                    updateNavigationButtons(foundRecord.getCreatedAt());
                } else {
                    Toolkit.getDefaultToolkit().beep();
                    JOptionPane.showMessageDialog(this,
                            "No record found for the searched criteria.",
                            "Search Results",
                            JOptionPane.WARNING_MESSAGE);
                }
            } catch (SQLException e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(this, "Database error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_jButtonSearchRecordActionPerformed

    private void loadRecord(Timestamp timestamp, Object sourceComponent) {
        try {
            Auction record = null;

            if (timestamp == null && sourceComponent == null) {
                // initial load - get latest
                record = AuctionDAO.getLatestAuction();
                if (record == null) {
                    JOptionPane.showMessageDialog(this, "No auctions found.", "Info", JOptionPane.INFORMATION_MESSAGE);
                    jButtonPreviousRecord.setEnabled(false);
                    jButtonNextRecord.setEnabled(false);
                    return;
                }
            } else if (sourceComponent == jButtonPreviousRecord) {
                record = AuctionDAO.getPreviousAuction(currentRecordCreatedAtTimestamp);
                if (record == null) {
                    JOptionPane.showMessageDialog(this, "You have reached the oldest record.", "Info", JOptionPane.INFORMATION_MESSAGE);
                    jButtonPreviousRecord.setEnabled(false);
                    return;
                }
            } else if (sourceComponent == jButtonNextRecord) {
                record = AuctionDAO.getNextAuction(currentRecordCreatedAtTimestamp);
                if (record == null) {
                    JOptionPane.showMessageDialog(this, "You have reached the newest record.", "Info", JOptionPane.INFORMATION_MESSAGE);
                    jButtonNextRecord.setEnabled(false);
                    return;
                }
            }

            if (record != null) {
                populateForm(record);
                updateNavigationButtons(record.getCreatedAt());
            }
        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Database error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void populateForm(Auction record) {
        jTextFieldAuctionId.setText(Integer.toString(record.getId()));
        jTextFieldAuctionTitle.setText(record.getTitle());
        jTextAreaAuctionDescription.setText(record.getDescription());
        jTextAreaAuctionDescription.setCaretPosition(0); // go back to the start

        Timestamp auctionDateTime = record.getAuctionDate();
        if (auctionDateTime != null) {
            jFormattedTextFieldAuctionDate.setValue(new Date(auctionDateTime.getTime()));
        } else {
            jFormattedTextFieldAuctionDate.setValue(null);
        }

        Timestamp createdAt = record.getCreatedAt();
        if (createdAt != null) {
            jFormattedTextFieldCreatedAt.setValue(new Date(createdAt.getTime()));
        } else {
            jFormattedTextFieldCreatedAt.setValue(null);
        }

        // **CRUCIAL:** Update current timestamp AFTER loading record
        currentRecordCreatedAtTimestamp = record.getCreatedAt();
        currentRecordId = record.getId();

        try {
            // 1. Fetch bids from database using BidDAO
            List<Bid> bids = BidDAO.getBidsForAuction(record.getId());

            // 2. Convert List<Bid> to DefaultListModel<String[]>
            DefaultListModel<String[]> model = new DefaultListModel<>();
            NumberFormat currencyFormat = NumberFormat.getCurrencyInstance(Locale.US);

            for (Bid bid : bids) {
                String formattedBidAmount = currencyFormat.format(bid.getBidAmount()); // convert BigDecimal to Currency String
                String[] row = new String[]{
                    bid.getBidderName(),
                    "", // leave empty if you have a placeholder column
                    "",
                    formattedBidAmount
                };
                model.addElement(row);
            }

            // 3. Assign the model to the JList (raw type needed if declared as JList<String>)
            JList rawList = jListBidRecords;
            rawList.setModel(model);

            // 4. Set your custom renderer to display String[] as multiple columns
            rawList.setCellRenderer(new MultiColumnBidsJListRenderer());

        } catch (SQLException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(null, "Error fetching bids: " + ex.getMessage());
        }

        System.out.println("Updated currentRecordCreatedAtTimestamp to: " + currentRecordCreatedAtTimestamp);
    }

    private void updateNavigationButtons(Timestamp currentCreatedAt) {
        try {
            boolean hasPrevious = AuctionDAO.getPreviousAuction(currentCreatedAt) != null;
            boolean hasNext = AuctionDAO.getNextAuction(currentCreatedAt) != null;
            jButtonPreviousRecord.setEnabled(hasPrevious);
            jButtonNextRecord.setEnabled(hasNext);
        } catch (SQLException e) {
            e.printStackTrace();
            jButtonPreviousRecord.setEnabled(false);
            jButtonNextRecord.setEnabled(false);
        }
    }

    private void showPopupMenu(MouseEvent e) {
        if (e.isPopupTrigger()) { // works for Win/Mac/Linux
            jPopupMenuForEditorPane.show(e.getComponent(), e.getX(), e.getY());
        }
    }

    private void promptQuit(JFrame uiInstance) {
        Toolkit.getDefaultToolkit().beep();
        String objButtons[] = {"Yes", "No"};
        int promptResult
                = JOptionPane.showOptionDialog(
                        uiInstance,
                        "Are you sure you want to exit?",
                        "Quit Confirmation",
                        JOptionPane.DEFAULT_OPTION,
                        JOptionPane.QUESTION_MESSAGE,
                        null,
                        objButtons,
                        objButtons[1]);
        if (promptResult == JOptionPane.YES_OPTION) {
            uiInstance.setVisible(false);
            uiInstance.dispose();
            System.exit(0);
        }
    }

    // Helper function to wrap text
    private List<String> wrapText(String text, int width) {
        List<String> lines = new ArrayList<>();
        if (text == null) {
            text = "";
        }
        while (text.length() > width) {
            int spaceIndex = text.lastIndexOf(' ', width);
            if (spaceIndex <= 0) {
                spaceIndex = width; // no space found
            }
            lines.add(text.substring(0, spaceIndex));
            text = text.substring(spaceIndex).trim();
        }
        if (!text.isEmpty()) {
            lines.add(text);
        }
        return lines;
    }

    /**
     * Justifies a line of text to fill a specific width by adding extra spaces
     * between words. Last line of paragraph is not justified (kept
     * left-aligned).
     */
    private List<String> justifyText(String text, int width) {
        List<String> words = Arrays.asList(text.split("\\s+"));
        List<String> lines = new ArrayList<>();
        int start = 0;

        while (start < words.size()) {
            int lineLength = words.get(start).length();
            int end = start + 1;
            while (end < words.size() && lineLength + 1 + words.get(end).length() <= width) {
                lineLength += 1 + words.get(end).length();
                end++;
            }

            List<String> lineWords = words.subList(start, end);
            StringBuilder line = new StringBuilder();
            int spacesNeeded = width - lineLength + (lineWords.size() - 1); // total extra spaces

            if (end == words.size() || lineWords.size() == 1) {
                // Last line or single word: left-align
                line.append(String.join(" ", lineWords));
            } else {
                // Fully justify
                int gaps = lineWords.size() - 1;
                int spacesPerGap = spacesNeeded / gaps + 1;
                int extraSpaces = spacesNeeded % gaps;

                for (int i = 0; i < lineWords.size(); i++) {
                    line.append(lineWords.get(i));
                    if (i < gaps) {
                        int gap = spacesPerGap + (i < extraSpaces ? 1 : 0);
                        line.append(" ".repeat(gap));
                    }
                }
            }

            lines.add(line.toString());
            start = end;
        }

        return lines;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupLookAndFeelOptions;
    private javax.swing.JButton jButtonAddRecord;
    private javax.swing.JButton jButtonDeleteRecord;
    private javax.swing.JButton jButtonEditRecord;
    private javax.swing.JButton jButtonExit;
    private javax.swing.JButton jButtonNextRecord;
    private javax.swing.JButton jButtonPreviousRecord;
    private javax.swing.JButton jButtonPrintRecord;
    private javax.swing.JButton jButtonSearchRecord;
    private javax.swing.JCheckBox jCheckBoxIncludeAuctionBidRecords;
    private javax.swing.JEditorPane jEditorPaneHelpContents;
    private javax.swing.JFormattedTextField jFormattedTextFieldAuctionDate;
    private javax.swing.JFormattedTextField jFormattedTextFieldCreatedAt;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelBidRecordsListHeaderBidderName;
    private javax.swing.JLabel jLabelNextIcon;
    private javax.swing.JLabel jLabelPreviousIcon;
    private javax.swing.JList<String> jListBidRecords;
    private javax.swing.JMenuItem jMenuItemCopy;
    private javax.swing.JMenuItem jMenuItemPrint;
    private javax.swing.JMenuItem jMenuItemSelectAll;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanelBidRecordListHeader;
    private javax.swing.JPanel jPanelRecordPrintOptions;
    private javax.swing.JPopupMenu jPopupMenuForEditorPane;
    private javax.swing.JRadioButton jRadioButtonMetalLaf;
    private javax.swing.JRadioButton jRadioButtonWindowsClassicLaf;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPaneBidRecords;
    private javax.swing.JTabbedPane jTabbedPaneFormPages;
    private javax.swing.JTextArea jTextAreaAuctionDescription;
    private javax.swing.JTextField jTextFieldAuctionId;
    private javax.swing.JTextField jTextFieldAuctionTitle;
    // End of variables declaration//GEN-END:variables
}
